# Generated by Django 3.1.5 on 2021-02-20 10:39

from django.db import migrations, models
import sauce_shopping.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210220_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=sauce_shopping.storage_backend.PublicMediaStorage(), upload_to=''),
        ),
    ]
